db:
  image: postgres:9.3
  environment:
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: password
  ports:
    - "5432:5432"
  volumes_from:
    - dbdata

dbdata:
  image: busybox
  volumes:
    - /var/lib/postgresql/data

